
replicaCount: 3
namespace:
  name: prod
image:
  repository: techtrends
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 7111
  targetPort: 3111
  protocol: TCP

resources: 
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 300Mi

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz


